stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/data.csv
    outs:
      - data/processed/data.csv
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/raw/data.csv
    params:
      - train.model
      - train.random_state
      - train.n_estimators
      - train.max_depth
    outs:
      - models/model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/raw/data.csv
    - models/model.pkl
    - src/evaluate.py
